project_name = "{{ name }}"
author_name = "erick sa√∫l"
project_namespace = "{{ namespace }}"
namespace = "arti"
author_github = "@erick3900"
cpp_std = "20"
project_version = "0.0.1"
project_description = ""
conan_libs = "fmt/10.0.0"
conan_generator_type = "CMakeDeps\nCMakeToolchain"
